apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
    #  superuserSecret:
    #name: superuser-secret

  bootstrap:
    initdb:
      database: process-engine
      owner: app

  storage:
    size: 1Gi
