apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
    #  superuserSecret:
    #name: superuser-secret

    #  bootstrap:
    #initdb:
    #  database: app
    #  owner: app
    #  secret:
    #    name: app-secret

  storage:
    size: 1Gi
